config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:update, :show, :index]
  resources :lists do
    resources :items, only: [:create, :destroy] do
      patch "complete" => "items#complete", as: :complete_item
      patch "incomplete" => "items#incomplete", as: :incomplete_item
    end
  end

get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  belongs_to :user

  default_scope { order('updated_at DESC') }

  def destruction_time
      7.days+self.created_at
  end


end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  belongs_to :user

  default_scope { order('created_at DESC') }


   validates :title, length: { minimum: 5 }, presence: true
   validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :lists, dependent: :destroy
  has_many :items, dependent: :destroy

   def admin?
     role == 'admin'
   end

   def moderator?
     role == 'moderator'
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

   rescue_from Pundit::NotAuthorizedError do |exception|
     redirect_to root_url, alert: exception.message
   end

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  respond_to :html, :js
  def index
    @items = Item.all
    authorize @items
  end

  def show
    @list = List.find(params[:list_id])
    @item = Item.find(params[:id])
  end

  def new
      @list = List.find(params[:list_id])
      @item = Item.new
      @item = @list.item
      authorize @item
  end

  def create
     @list = List.find(params[:list_id])
     @items = @list.items
     @item = current_user.items.build(item_params)
     @item.list = @list
     authorize @item
     if @item.save
       flash[:notice] = "To-Do Item was saved."

     else
       flash[:error] = "There was an error saving the To-Do Item. Please try again."

     end
   end

def complete
  @list = List.find(params[:list_id])
  @item = Item.find(params[:item_id])
  @item.completed = true
    authorize @item
  if @item.save
    respond_with(@item) do |format|
      format.html { render @item }
    end
  else

  end
end

def incomplete
  @list = List.find(params[:list_id])
  @item = Item.find(params[:item_id])
  @item.completed = false
    authorize @item
  if @item.save
    respond_with(@item) do |format|
      format.html { render @item }
    end
  else

  end
end


 def update
     @item = Item.find(params[:id])
     authorize @item
     if @item.update_attributes(item_params)
       flash[:notice] = "To-Do List was updated."
       redirect_to @item
     else
       flash[:error] = "There was an error saving the To-Do list. Please try again."
       render :edit
     end
   end


  def destroy

     @list = List.find(params[:list_id])
     @item = @list.items.find(params[:id])
     authorize @item

     if @item.destroy
       flash[:notice] = "Todo Item was removed."

     else
       flash[:error] = "Todo Item couldn't be deleted. Try again."

     end

     respond_with(@item) do |format|
       format.html { redirect_to @list }
     end

   end



  private

  def item_params
    params.require(:item).permit(:body)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
    authorize @lists

  end

  def show
    @list = List.find(params[:id])
    authorize @list
  end

  def new
    @list = List.new
    authorize @list
  end

  def create
     @list = current_user.lists.build(list_params)
     authorize @list
     if @list.save
       flash[:notice] = "To-Do List was saved."
       redirect_to @list
     else
       flash[:error] = "There was an error saving the To-Do list. Please try again."
       render :new
     end
   end

 def edit
     @list = List.find(params[:id])
  end

   def update
     @list = List.find(params[:id])
     authorize @list
     if @list.update_attributes(list_params)
       flash[:notice] = "To-Do List was updated."
       redirect_to @list
     else
       flash[:error] = "There was an error saving the To-Do list. Please try again."
       render :edit
     end
   end

  private

  def list_params
    params.require(:list).permit(:title)
  end

end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
   before_action :authenticate_user!

   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end

   private

   def user_params
     params.require(:user).permit(:name)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
 module ApplicationHelper
   def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end

  def markdown(text)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render text).html_safe
  end

    def my_name
      :'Marc Dysart'
    end
 end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_completeditem.html.erb
<%= content_tag :tr, class: 'media item-complete', id: "item-#{item.id}" do %>
     <% if policy(item).complete? %>
     <td><%= link_to(list_item_incomplete_item_path(item.list, item), method: :patch, remote: true) do
       check_box_tag 'completed', "1", true, id: "item-complete#{item.id}"
     end %></td>
     <% end %>
     <td><%= markdown item.body  %></td>
     <td><%= time_ago_in_words(item.created_at+1.week) %></td>
     <td>
     <% if policy(item).destroy? %>
       <%= link_to "Delete", [item.list, item], method: :delete, remote: true %>
     <% end %>
     </td>


<% end %>

app/views/items/_form.html.erb
 <%= form_for [list, item], remote: true do |f| %>
  <% if list.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(list.errors.count, "error") %>.</h4>
      <ul>
        <% list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <form class="form-inline" role="form">
    <div class="form-group">
       <%= f.label :"Enter New To-Do Item" %>
       <div class="row">
         <div class="col-xs-6">
            <%= f.text_field :body, class: 'form-control', placeholder: "Enter To-Do Item" %>
        </div>
        <div class="col-xs-2">
          <%= f.submit "Save To-Do Item", class: 'btn btn-default' %>

        </div>
        <div class="col-xs-4">
        </div>
      </div>
    </div>

  </form>


<% end %>

app/views/items/_item.html.erb
   <%= content_tag :tr, class: 'media item-incomplete', id: "item-#{item.id}" do %>
        <% if policy(item).complete? %>
        <td><%= link_to(list_item_complete_item_path(item.list, item), method: :patch, remote: true) do
          check_box_tag 'completed', "1", false, id: "item-complete#{item.id}"
        end %></td>
        <% end %>
        <td><%= markdown item.body  %></td>
        <td><%= time_ago_in_words(item.created_at+1.week) %></td>
        <td>
        <% if policy(item).destroy? %>
          <%= link_to "Delete", [item.list, item], method: :delete, remote: true %>
        <% end %>
        </td>


  <% end %>

app/views/items/complete.js.erb
  // $('#item-complete' +<%= @item.id %>).on('change', function(){
  //   $('#item-' +<%= @item.id %>).remove().insertAfter('#item-' +<%= @item.id %>)
  // });

// $(#container .row:first").remove().insertAfter($("#container .row:last));
// $('#js-table tbody').prepend("<%= escape_javascript(render(@item)) %>");


// $('.question_1_checkbox').on('change', function(){
//   $(this.data('target')).toggle();
// });



// $('#item-complete' +<%= @item.id %>).on('change', function(){
//   console.log(class);
//   if(this.checked){
//     $('#item-' +<%= @item.id %>).css('color': 'red');
//   }
// });

// $('#item-complete' +<%= @item.id %>).change( function(){
//   if(this.checked){
//     $('#item-' +<%= @item.id %>).remove();
//     $('#js-table tbody').append("<%= escape_javascript(render(@item)) %>");
//     $('#item-' +<%= @item.id %>).css({"color": "red", "text-decoration": "line-through"});
//   }
// });

<% if @item.completed? %>
 if($('#item-complete' +<%= @item.id %>).prop('checked')) {
   $('#item-' +<%= @item.id %>).remove();
   $('#js-table tbody').prepend("<%= escape_javascript(render(@item)) %>");
   $('#item-' +<%= @item.id %>).css({"color": "black", "text-decoration": "none"});
   $('#item-complete' +<%= @item.id %>).prop('checked', false)
   <% @item.completed = false %>
  }
 else {
   $('#item-' +<%= @item.id %>).remove();
   $('#js-table tbody').append("<%= escape_javascript(render(@item)) %>");
   $('#item-' +<%= @item.id %>).css({"color": "red", "text-decoration": "line-through"});
   $('#item-complete' +<%= @item.id %>).prop('checked', true)
   <% @item.completed = true %>
 }

<% else %>
  $('#item-' +<%= @item.id %>).remove();
  $('#js-table tbody').prepend("<%= escape_javascript(render(@item)) %>");
  $('#item-' +<%= @item.id %>).css({"color": "black", "text-decoration": "none"});
<% end %>

app/views/items/create.js.erb
 <% if @item.valid? %>
    $('#js-table tbody').prepend("<%= escape_javascript(render(@item)) %>");
    $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { list: @list, item: @new_item }) %>");
 <% else %>
   $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { list: @list, item: @item }) %>");
 <% end %>


// $('#js-table tbody').append('<tr />').children('tr.last').append("<%= escape_javascript(render(@item)) %>");

app/views/items/destroy.js.erb
 <% if @item.destroyed? %>
  $('#item-' +<%= @item.id %>).hide();
 <% else %>
   $('#item-' +<%= @item.id %>).prepend("<div class='alert alert-error'><%= flash[:error] %></div>");
 <% end %>

app/views/items/incomplete.js.erb
  // $('#item-complete' +<%= @item.id %>).on('change', function(){
  //   $('#item-' +<%= @item.id %>).remove().insertAfter('#item-' +<%= @item.id %>)
  // });

// $(#container .row:first").remove().insertAfter($("#container .row:last));
// $('#js-table tbody').prepend("<%= escape_javascript(render(@item)) %>");


// $('.question_1_checkbox').on('change', function(){
//   $(this.data('target')).toggle();
// });



// $('#item-complete' +<%= @item.id %>).on('change', function(){
//   console.log(class);
//   if(this.checked){
//     $('#item-' +<%= @item.id %>).css('color': 'red');
//   }
// });

// $('#item-complete' +<%= @item.id %>).change( function(){
//   if(this.checked){
//     $('#item-' +<%= @item.id %>).remove();
//     $('#js-table tbody').append("<%= escape_javascript(render(@item)) %>");
//     $('#item-' +<%= @item.id %>).css({"color": "red", "text-decoration": "line-through"});
//   }
// });

<% if @item.completed? %>
 if($('#item-complete' +<%= @item.id %>).prop('checked')) {
   $('#item-' +<%= @item.id %>).remove();
   $('#js-table tbody').prepend("<%= escape_javascript(render(@item)) %>");
   $('#item-' +<%= @item.id %>).css({"color": "black", "text-decoration": "none"});
   $('#item-complete' +<%= @item.id %>).prop('checked', false)
   <% @item.completed = false %>
  }
 else {
   $('#item-' +<%= @item.id %>).remove();
   $('#js-table tbody').append("<%= escape_javascript(render(@item)) %>");
   $('#item-' +<%= @item.id %>).css({"color": "red", "text-decoration": "line-through"});
   $('#item-complete' +<%= @item.id %>).prop('checked', true)
   <% @item.completed = true %>
 }

<% else %>
  $('#item-' +<%= @item.id %>).remove();
  $('#js-table tbody').prepend("<%= escape_javascript(render(@item)) %>");
  $('#item-' +<%= @item.id %>).css({"color": "black", "text-decoration": "none"});
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
      <ul class="nav nav-tabs">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "My To-Do Lists", lists_path %></li>

        <div class="pull-right user-info">
           <% if current_user %>
             Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
       </ul>


       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>


    <%= yield %>
  </div>

</body>
</html>

app/views/lists/_form.html.erb
<%=  form_for list do |f| %>
  <% if list.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(list.errors.count, "error") %>.</h4>
      <ul>
        <% list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_group_tag(list.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter a To-Do List title" %>
   <% end %>

    <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
      <%= link_to "Cancel", :back, {:class=>"btn btn-default"} %>
    </div>

  <% end %>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<div class="row">
   <div class="col-md-4">
    <p>Guidelines for Lists</p>
    <ul>
      <li>Make sure your to-do item can be done in 7 days</li>
      <li>This item will be deleted after 7 days.</li>
      <li>The title should be at least 5 characters long</li>

    </ul>
  </div>

  <div class="col-md-8">

    <%= render partial: 'form', locals: { list: @list } %>
  </div>
</div>

app/views/lists/index.html.erb
<h1>All To-Do Lists</h1>
 <% if policy(List.new).create? %>
 <%= link_to "New To-Do List", new_list_path, class: 'btn btn-success' %>
 <% end %>
<% @lists.each do |list| %>
<% if current_user.present? && (current_user == list.user || current_user.admin?) %>
     <div class="media">
     <div class="media-body">
       <h4 class="media-heading">
         <%= markdown link_to list.title, list %>
        <small>
         submitted <%= time_ago_in_words(list.created_at) %> ago by <%= list.user.name %><br/>
         <%= list.items.count %> To-Do Items
       </small>
       </h4>
     </div>
   </div>
<% end %>
<% end %>

app/views/lists/new.html.erb
 <h1>New List</h1>

 <div class="row">
    <div class="col-md-4">
     <p>Guidelines for Lists</p>
     <ul>
       <li>Make sure your to-do item can be done in 7 days</li>
       <li>This item will be deleted after 7 days.</li>
       <li>The title should be at least 5 characters long</li>
     </ul>
   </div>

   <div class="col-md-8">
     <%= render partial: 'form', locals: { list: @list } %>
   </div>
 </div>

app/views/lists/show.html.erb
  <div class='js-items'>
      <table id='js-table' class="table table-hover">
            <h1 class = "text-center"><%= markdown @list.title %>
            <%= link_to "Edit List Name", edit_list_path(@list), class: 'btn btn-success' %></h1>
            <thead>
              <tr>
                <th>Complete</th>
                <th>To Do Items</th>
                <th>Time till Self-Destruction</th>
                <th>Delete</th>
              </tr>
            </thead>
            <tbody>
              <% @list.items.each do |item| %>
                <% unless item.completed? %>
                    <%= render  partial: 'items/item', locals: {item: item} %>
                 <% end %>
               <% end %>

              <% @list.items.each do |item| %>
                <% if item.completed? %>
                    <%= render  partial: 'items/completeditem', locals: {item: item} %>
                 <% end %>
               <% end %>

            </tbody>
          </table>
  </div>

  <div class="new-item">
  <%= form_for [@list, @list.items.new], remote: true do |f| %>

  <% if @list.errors.any? %>
    <div class="alert alert-danger">
      <h4>There are <%= pluralize(list.errors.count, "error") %>.</h4>
      <ul>
        <% @list.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form class="form-inline" role="form">
    <div class="form-group">
       <%= f.label :"Enter New To-Do Item" %>
       <div class="row">
         <div class="col-xs-6">
            <%= f.text_field :body, class: 'form-control', placeholder: "Enter To-Do Item" %>
        </div>
        <div class="col-xs-2">
          <%= f.submit "Save To-Do Item", class: 'btn btn-default' %>
        </div>
        <div class="col-xs-4">
        </div>
      </div>
    </div>
  </form>
 <% end %>
  </div>

app/views/welcome/about.html.erb
<h1>About Blocitoff</h1>
<p>Created by: <%= my_name %></p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron welcome-image">
  <h1>Blocitoff</h1>
  <p>Blocitoff is a self-destructing to-do list that deletes items after 7 days.  A tool to keep you focused on the things that really matter.<p>
  <p>
      <%= link_to "Sign In", "#", class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", "#" , class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-6">
    <h2>Keep your to-do lists here!</h2>
    <p>A To-Do lists to remind you to do this week only!  For the little things.</p>
  </div>
  <div class="col-md-6">
    <h2>Sign up for free!</h2>
    <p>People have been raving about how organized they have been since using Blocitoff</p>
  </div>
</div>